# Using "merge_request into main" workflow (https://docs.gitlab.com/ee/ci/yaml/workflow.html)
include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

variables:
  JULIA_DEPOT_PATH: '$CI_PROJECT_DIR/.julia'

stages:
  - build
  - test
  - deploy

# GitLab CI: Auto dependency updates https://thacoon.com/posts/gitlab-ci-auto-dependency-update/
# `GIT_PUSH_TOKEN` CI/CD variable = personal access token (PAT) with write access
update-julia:
  image: julia:1.7.3
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    JULIA_PKG_PRECOMPILE_AUTO: 0
  script:
    - apt-get update && apt-get install -y git
    - julia --color=yes --threads=auto --project=@. -e 'import Pkg; Pkg.update()'
    # Open a MR when there is a update, requires GIT_PUSH_TOKEN` CI/CD variable = personal access token (PAT) with write access
    - |
      if [[ -n $(git status --porcelain) ]]; then
        echo "Commiting updates"
        NEW_BR=auto-update-$(date '+%Y-%m-%d-%H-%M-%S')
        git config --global user.name "${GITLAB_USER_NAME}"
        git config --global user.email "${GITLAB_USER_EMAIL}"
        git checkout -b ${NEW_BR}
        git add .
        git commit -m "${NEW_BR}"
        git push "https://${GITLAB_USER_NAME}:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}" \
            -o merge_request.create \
            -o merge_request.target="${CI_DEFAULT_BRANCH}" \
            -o merge_request.merge_when_pipeline_succeeds \
            -o merge_request.remove_source_branch \
            -o merge_request.title="${NEW_BR}" \
            -o merge_request.label="automated update" \
            -o merge_request.assign="${GITLAB_USER_NAME}"
        exit;
      else
        echo "no change, nothing to commit"
      fi

jupyter-book:
  image: registry.gitlab.com/sosiristseng/docker-juliabook:1.7.3.12
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    - key:
        files:
          - Project.toml
          - Manifest.toml
      paths:
        - .julia/
    - key:
        files:
          - Project.toml
          - Manifest.toml
      paths:
        - _build/.jupyter_cache/
  before_script:
    - julia --color=yes --project="" -e 'import Pkg; Pkg.add("IJulia"); Pkg.build("IJulia")'
    - julia --threads=auto --color=yes --project=@. -e 'import Pkg; Pkg.instantiate()'
    - jupyter-book build docs/ --warningiserror --keep-going -v
  script:
    - echo "Done!"

pages:
  extends: jupyter-book
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
  script:
    - mv docs/_build/html public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip -f -k {} \; -exec brotli -f -k {} \; || echo 'Compression failed. Skipping...'
  artifacts:
    paths:
      - public
